### PR TITLE
Move Utility and Sensor Logic to Modules

### PR DESCRIPTION
**Pull request by cmpadden**
- Move sensor interface code into the `sensors` directory
- Include third-party libraries in the `libraries` directory with respective licenses
- Update `upload` script to support new directory structure
- Update Python imports to support new directory structure

### CODE REVIEW

**Comment by cmpadden** [comment]
@fpgirard I've included third party libraries (bme680, usmbus) in the repository, and have updated the upload script to support the new directory structure. When you get the chance could you take a look at the changes?

One thing that is acting up is that the first `ampy` command after flashing Micropython seems to fail. Have you experience this problem?

```
ampy.pyboard.PyboardError: could not enter raw repl 
```

**Comment by fpgirard** [comment]
Yea - try the argument ‘-d 0.5’…..  it’s a somewhat well documented bug.   Or are you already doing this?

On June 18, 2019 at 9:48:35 PM, Colton (notifications@github.com) wrote:

@fpgirard I've included third party libraries (bme680, usmbus) in the repository, and have updated the upload script to support the new directory structure. When you get the chance could you take a look at the changes?

One thing that is acting up is that the first ampy command after flashing Micropython seems to fail. Have you experience this problem?

ampy.pyboard.PyboardError: could not enter raw repl

**Comment by cmpadden** [comment]
The upload script is no longer throwing the error with the added delay.

Another thing that I'd like your opinion on: I added the third-party libraries to a directory called `libraries`, so if you want to use the `usmbus` library you would use `from libraries.usmbus import SMBus`. What are your thoughts on this name, do you think something else would be more intuitive?

**Comment by fpgirard** [comment]
Make it ‘lib’?  Maybe I don’t know python conventions so if ‘lib’ sounds too c/c++, then we should use ‘libraries’.   This also sets us up to use ‘bin’.

I think that it also makes sense to put the PMSA003.py ‘library’ in there too.   

Then pm25.py in ‘./sensors’ basically calls this class.  

Cleaning stuff up is such a big help.

This weekend, we can test the capacitive touch and baseline values.  I head to NY Friday morning and am hosting friends from the city...

P



On June 19, 2019 at 9:32:16 AM, Colton (notifications@github.com) wrote:

The upload script is no longer throwing the error with the added delay.

Another thing that I'd like your opinion on: I added the third-party libraries to a directory called libraries, so if you want to use the usmbus library you would use from libraries.usmbus import SMBus. What are your thoughts on this name, do you think something else would be more intuitive?

**Comment by cmpadden** [comment]
I've renamed _libraries_ to _lib_, and _utilities_ to _bin_. I've also moved the `config` file to the root directory, as it didn't seem to fit the theme of the _bin_ directory (this can be moved back if desired).

At this point we're looking like this:
```
$ tree --dirsfirst
.
├── bin
│   ├── build
│   │   └── esp32-v1.10-194-g41e7ad6.bin
│   ├── hwtest.py
│   ├── setgrp.py
│   ├── testiot.py
│   └── upload
├── lib
│   ├── bme680
│   │   ├── LICENSE.txt
│   │   ├── __init__.py
│   │   └── constants.py
│   ├── pmsa003
│   │   └── pmsa003.py
│   ├── usmbus
│   │   ├── LICENSE
│   │   └── __init__.py
│   └── __init__.py
├── sensors
│   ├── __init__.py
│   ├── analog.py
│   ├── dht11.py
│   ├── enviro.py
│   ├── pm25.py
│   ├── stub.py
│   ├── tph.py
│   └── tphg.py
├── static
│   ├── Layla-905.jpg
│   └── baseplate.pdf
├── LICENSE.txt
├── README.md
├── boot.py
├── config-generic.py
├── config.py
├── iot.py
├── main~.py
├── sleep.py
├── wake.py
└── webrepl_cfg.py
```

**Pull request merged**
