### PR TITLE
Upgrade Script Enhancements

### PR DESCRIPTION
**Pull request by cmpadden**
**Work In Progress**

- [x] Add command line argument for target device
- [x] Add command line argument to either `upload` or `upgrade` (this ended up being `reinstall`)
- [x] Make Ampy the only required dependency
- [x] Support Python 2 in `setgrp` to remove local dependency of Python 3

### CODE REVIEW

**Comment by cmpadden** [comment]
@michaelbartholic & @fpgirard,

When you have a moment, could you please review these changes?

For the `setgrp` script, I have removed the `requests` module dependency as that is not initially installed, and I have modified it to use Python 2 instead of Python 3. With some more tweaks we could make the script run on both 2 and 3, but that hasn't been done yet.

The `upload` script now takes two arguments. The first being the target `device`, and the second being an optional parameter to erase and re-install MicroPython before uploading the code to the device. When this option is not specified, then code will still be uploaded to the device, and the `setgrp` script will be triggered.

**Review by theFestest — COMMENTED** [review]
This is a big improvement. I really like what you've done here. As for the note about python2/3, I think it will be important to support both through python2's EOL in a few months as everyone begins to focus on 3 exclusively. Unfortunately, my own empirical evidence shows that the average person is about 50/50 having 2 or 3 natively installed right now. For the time being, I think expecting python2 is reasonable for our use cases. 

My only real concern at the moment is about user discovery of the DEVICE path. In my opinion, it can be pretty opaque which device is the right one. Perhaps noting something like "make sure the monitor is the only USB device attached" and then automatically select the only usbserial device? Or enumerating them for the user and asking for a choice? What do you think?

**Comment by cmpadden** [comment]
Thanks!

As for detecting the USB device, there are a few ways to do that. A while back I actually wrote a small script that makes a list of the devices, prompts the user to plug in the device, looks to see the new device, and then connects them to `screen`. Alternatively, this could probably also be done by watching the USB events. We may be able to do something similar in the upgrade script.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import glob
import time
import subprocess

BAUD = 115200

# list of terminal devices
ttys_before = glob.glob('/dev/tty*')

# prompt user to plug in the device, and re-check ttys
print('Plug in your microcontroller, then press <ENTER>.')
input()

# find new terminal entries, retry until a new device is shown...
ttys_diff = []
while True:
    ttys_new = glob.glob('/dev/tty*')
    ttys_diff = [t for t in ttys_new if t not in ttys_before]
    if ttys_diff:
        break
    else:
        time.sleep(2.5)
        print('No device was detected! Trying again...')

# assumes only one device
print('Your device was detected at: {}'.format(ttys_diff[0]))

# prompt user to connect to the device
print('Press <ENTER> if you would like to connect to this device via `screen`')
input()
subprocess.check_output(['screen', ttys_diff[0], str(BAUD)])
```

**Comment by theFestest** [comment]
That would be perfect actually. That’s just the right level of interaction I think and the only assumptions it makes seem relatively safe. It strikes me that looking at the USB message log would also probably be pretty effective but maybe more complex to implement. This seems like it would work well.

**Comment by fpgirard** [comment]
I'm back from Wisconsin and now in jury duty for the remainder of the day.  Colton - thanks for tackling this tool.   I'll clone it tomorrow and test it on the esp32.  I agree with Michael though - relying on the user to properly identify the correct serial interface is problematic.  At this point, we are requiring that they do have some minimal skills - like using Terminal or cmd...

**Comment by cmpadden** [comment]
FYI, I've modified the `setgrp` script to work with either Python 2 or 3.

This was done by conditionally importing the `urllib` library depending on the version, and importing the `print` function from the _future_.

```
from __future__ import print_function
```

```
if sys.version_info[0] == 3:                                                    
    from urllib.request import urlopen, Request                                 
else:                                                                           
    from urllib2 import urlopen, Request  
```

**Comment by theFestest** [comment]
Good integration of the device detection stuff. I like it. I won’t be able to get to running it today, but I will try tomorrow and hopefully Pascal and I can both have feedback. It looks pretty solid.

**Comment by cmpadden** [comment]
Please take a look at the `bin/upload.py` script.

It should be able to do everything the `upload` script did, as well as detecting the device being plugged in.

Example usages:
```
# Upload files and automatically detect device
python bin/upload.py

# Upload files to specified device
python bin/upload.py --device /dev/tty.usbserial-1410

# Upload files to specified device, and re-install MicroPython
python bin/upload.py --device /dev/tty.usbserial-1410 --reinstall
```

EDIT: so far I have only tested this with Python 2, but I tried to use features available in both versions. There will likely still need to be changes to get it to work with 3.

**Comment by cmpadden** [comment]
@michaelbartholic, @fpgirard ,

I've included a file in the root directory named, `update.command`. This should allow users to double click this file to begin the device updating process.

**Comment by theFestest** [comment]
This took me a little longer to get to than I'd hoped since my python installation was _very_ messed up apparently, but today I finally got to take a look at it all––

I added checking/trying to install the python dependencies to `update.command`, I figure its inexpensive to check each time and the output will just scroll past if there's no interaction needed. I tested this by manually removing the packages and the script reinstalled them without any interaction. Though, perhaps there's a better location to include this type of thing so it runs cross-platform.

I tested both `python bin/upload.py` and `python bin/upload.py --reinstall` for both python2 and python3 and there were only minor issues with python3 during the hardware test portion. I wasn't clear on exactly how to fix this so I'll just leave the error here.
```
Traceback (most recent call last):
  File "/Users/michaelbartholic/git/air-quality/bin/upload.py", line 216, in <module>
    main(sys.argv)
  File "/Users/michaelbartholic/git/air-quality/bin/upload.py", line 207, in main
    device_id = ampy_hwtest(device)
  File "/Users/michaelbartholic/git/air-quality/bin/upload.py", line 127, in ampy_hwtest
    chip_id = r.split(os.linesep)[0].split(':')[1].strip()
TypeError: a bytes-like object is required, not 'str'
```

Otherwise, I do notice that the subprocesses are sending all output to stderr (because it doesn't seem possible to use stdout there?) and this works, but it does make all the output appear as error output (for example, all red text) depending on your terminal settings.

Overall everything looks great and seems to work well. The core functionality runs on both 2 and 3.

**Comment by theFestest** [comment]
Good point, it seems to be packaged with all python installations since about 2014 but not necessarily installed automatically. This should be safer on macOS and Linux, Windows is still an open question.

**Comment by cmpadden** [comment]
@theFestest

Had a busy weekend, so I'm finally getting around to looking at these changes more thoroughly. Looks good!

I like the idea of ensuring the dependencies upfront. I was going to add checks in the code to make sure the tools were installed before execution, and then failing if they weren't there. Those could still be added, but I think that this will make the usage of the `update` tool more convenient.

Do you, or someone we know, have access to a windows environment to test the scripts? I have a windows ISO somewhere, and could install it on my desktop, but that'd be a bit of a hassle.

What do you think about merging this into master, and then create a separate pull request for adding windows support.

**Comment by cmpadden** [comment]
@theFestest, as for redirecting the output. I was redirecting `stderr` to `stdout` to suppress it.

See this StackOverflow answer: https://stackoverflow.com/a/38384613/10044859

> Use subprocess.check_output (new in python 2.7). It will suppress stdout and raise an exception if the command fails. (It actually returns the contents of stdout, so you can use that later in your program if you want.)

**Comment by theFestest** [comment]
I have Bootcamp with Windows 10 on my primary laptop, so I could install things and test in there without too much trouble. (With VMware fusion you can actually boot the partition as a VM in macOS as well which is SUPER nice, if you've haven't seen that)

This seems good to merge into master and then we can open up windows support as another.

As for the output redirection, that makes sense. Perhaps something was just a bit odd with how my IDE was displaying it because I was getting the output 
```
INFO:root:Target device: /dev/tty.usbserial-1460
INFO:root:Creating directory: ./sensors
INFO:root:Directory, ./sensors, already exists
INFO:root:Creating directory: ./bin
INFO:root:Directory, ./bin, already exists
INFO:root:Creating directory: ./static
INFO:root:Directory, ./static, already exists
```
and such as red "exception" output as if it was coming from stderr. I didn't notice anything in the terminal but figured it was just due to my limited output color profile.

**Comment by cmpadden** [comment]
@theFestest, FYI, the `pip install` commands failed for me due to permission issues.

```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pyserial-3.4.dist-info'
Consider using the `--user` option or check the permissions.
```

Following the output's advice, this was resolved by changing the command to the following:
```
python -m pip install --user ampy
```

**Pull request merged**
