### PR TITLE
Leverage Capacitive Touch for Upgrade

### PR DESCRIPTION
**Pull request by cmpadden**
Configure `main` so that the device can be booted into upgrade mode through capacitive touch.

- [x] Determine if we can use interrupts with the TouchPad object
- [x] Migrate configuration items to the `config.py` file
- [x] Confirm thresholds of touch are similar on other ESP32s

### CODE REVIEW

**Comment by fpgirard** [comment]
Colton - these are great strides.   At some point, perhaps we should make main~.py as main.py when we get to that point where it’s a stable release.

This weekend, I will review the latest on the MicroPython releases.  The current build is a ‘latest-release’ not a ’stable’ release and the distro is now at 1.11

Next week is much more open for me - let’s build you a real AQ monitor - with all the sensors!

In the meantime, the two monitors are chugging along without problems… who knew.

pas





On June 20, 2019 at 5:05:53 PM, Colton (notifications@github.com) wrote:

 Determine if we can use interrupts with the TouchPad object
 Migrate configuration items to the config.py file
 Confirm thresholds of touch are similar on other ESP32s
You can view, comment on, or merge this pull request online at:

  https://github.com/GeorgetownMakerHubOrg/air-quality/pull/5

Commit Summary

Example of using TouchPad for Upload
File Changes

M main~.py (37)
Patch Links:

https://github.com/GeorgetownMakerHubOrg/air-quality/pull/5.patch
https://github.com/GeorgetownMakerHubOrg/air-quality/pull/5.diff

**Comment by cmpadden** [comment]
@fpgirard I confirmed that that capacitive touch seems to be working.

When connected to the REPL, if I press CTRL-D to initiate a soft-reset and hold the wire then it will start the `ap` and `webrepl`. If I do not hold the wire, then it runs `wake.main()`.

Is this behavior aligned with what you expected?

**Comment by fpgirard** [comment]
That’s exactly what we want - now folks can have the monitor act as a router and we can attach to its SSID and upload code.

Woot!
On July 1, 2019 at 2:43:34 PM, Colton (notifications@github.com) wrote:

@fpgirard I confirmed that that capacitive touch seems to be working.

When connected to the REPL, if I press CTRL-D to initiate a soft-reset and hold the wire then it will start the ap and webrepl. If I do not hold the wire, then it runs wake.main().

Is this behavior aligned with what you expected?

**Comment by fpgirard** [comment]
Good.




On July 1, 2019 at 8:08:17 PM, Colton (notifications@github.com) wrote:

Merged #5 into master.

**Pull request merged**
